### ISSUE TITLE
Compatability with Leaflet 0.7.x

### ISSUE THREAD

**Issue by kasperg** [lennardv2/Leaflet.awesome-markers#24]
Thank you for the markers. They look great.

Is the plugin compatible with the latest version of Leaflet (0.7.1)? I tried to use it myself and got some strange results.

I also [forked the JSFiddle and updated to Leaflet 0.7.1](http://jsfiddle.net/zBRXJ/). Here the markers do not display at all. I did not update the javascript code as I could not spot any differences in the API here.

![awesome_makrers_leaflet_071](https://f.cloud.github.com/assets/73966/1937835/034b0b14-7f33-11e3-8863-064b2ca3a1ae.png)

**Comment by gerbsen** [comment]
Same problem here :/

**Comment by analytically** [comment]
+1

**Comment by lennardv2** [comment]
Hi!

I just tried Leaflet 1.7.1 & 1.7.2 on to examples and it just works fine. Here is the updated JSFiddle:

http://jsfiddle.net/VPzu4/174/

It's not working in your JSFiddle because you first included the awesomemarkers.js and then the leaflet.js, which results in: L is not defined. Reverse order works.

Can you tell me if this fiddle is working for you? then I can close this issue
